name: coverage

on:
  workflow_run:
    workflows: [work1,work2]
    types:
      - completed

jobs:
    codecoverage:
      name: Measure code coverage
      runs-on: ubuntu-20.04
      steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch
      - run: env  
      
      - name: Download artifacts
        id: download_artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          
          #        uses: dawidd6/action-download-artifact@v2
          #- run: |
          #gh run download -n artifact
          #env:
          #GH_TOKEN: ${{ github.token }}
          #uses: actions/download-artifact@v2
          #with: 
          #path: ./calc/coverage.out
          # name: "coverage-ubuntu-20.04-docker" 
      
      - name: Upload to CodeCov
        uses: codecov/codecov-action@v3 
        with:
          files: ./calc/coverage.out
