name: work1

on:
  push:
    branches: [main]
    paths:
      - "calc/**"
      - ".github/workflows/work1.yml"
  pull_request:
    branches: [main]
    paths:
      - "calc/**"
      - ".github/workflows/work1.yml"

jobs:
  build:
    name: Auto-testing Framework / ${{ matrix.os }} / ${{ matrix.runtime }}
    runs-on: ${{ matrix.os }}
    env:
      RUNTIME: ${{ matrix.runtime }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        runtime: ["docker", "containerd", "crio"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-go@v3
        with:
          go-version: v1.18

      - name: testing
        run: ./.github/workflows/echo.sh

      - name: Upload code coverage
        if: ${{ always() }}
        run: |
          go install github.com/modocache/gover@latest
          gover
          go tool cover -func=gover.coverprofile
        working-directory: calc
        env:
          GOPATH: /home/runner/go

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.runtime }}
          path: /
